que1- What are the benefits of the built-in array package, if any?

ans1- Arrays represent multiple data items of the same type using a single name. In arrays, the elements can be accessed randomly by using the index number. Arrays allocate memory in contiguous memory locations for all its elements. Hence there is no chance of extra memory being allocated in case of arrays. This avoids memory overflow or shortage of memory in arrays.

que2- What are some of the array package's limitations?

ans2- The number of elements to be stored in an array should be known in advance. An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot be modified. The memory which is allocated to it cannot be increased or decreased.

Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly.

Allocating more memory than the requirement leads to wastage of memory space and less allocation of memory also leads to a problem.

que3- Describe the main differences between the array and numpy packages.

ans3- The array package doesn't provide any help with numerical calculation with the items insdie it in number form while NumPy give you a wide variety of numerical operations. An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.

In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its column and row index, which makes it slightly time taking. Same goes with appending operation.

In case of array we do not form a tabular structure, while in numpy it forms a tabular structure

que4- Explain the distinctions between the empty, ones, and zeros functions.

ans4- The distinctions between the empty, ones, and zero functions are as follows :

- __Empty function__: An empty function is a function that does not contain any statement within its body. If you try to write a function definition without any statement in python ,it will return an error. To avoid this, we use pass statement. pass is a special statement in Python that does nothing. It only works as a dummy statement.
- __Ones function__: This function returns a new array of given shape and data type, where the element’s value is 1.
- __Zeros function__: This function returns a new array of given shape and data type, where the element’s value is 0.

que5- In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

ans5- fromfunction() function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z). Parameters : function : [callable] The function is called with N parameters, where N is the rank of shape.

que6- What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

ans6- 

In [2]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr + 1)

[2 3 4 5 6]


que7- Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

ans7- 

In [3]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
a = arr += 1
print(a)

SyntaxError: invalid syntax (Temp/ipykernel_1976/2844885719.py, line 3)

que8- Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

ans8- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. if longer strings is allocateed it might cause a computation problem basically increse the time complexity.

que9- What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

ans9- It will simply add or multiply element to element at same position.

In [5]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = arr1+arr2
arr1 = arr1*arr2
print(arr)
print("\n",arr1)

[[ 6  8]
 [10 12]]

 [[ 5 12]
 [21 32]]


que10- What is the best way to use a Boolean array to mask another array?

ans10- The best way to use a Boolean array to mask another array is by Using `masked_where` of numpy package.

que12- What is the dimensionality of a Boolean mask-generated array?

ans12- It will have same dimensionality as input array.

In [7]:
import numpy as np

arr = np.asarray([[[[1, 11], [2, 22], [3, 33]],
                   [[4, 44], [5, 55], [6, 66]]],
                  [[[7, 77], [8, 88], [9, 99]],
                   [[0, 32], [1, 33], [2, 34]]]])

masked_arr = np.ma.masked_less(arr, 3)
print(masked_arr)

[[[[-- 11]
   [-- 22]
   [3 33]]

  [[4 44]
   [5 55]
   [6 66]]]


 [[[7 77]
   [8 88]
   [9 99]]

  [[-- 32]
   [-- 33]
   [-- 34]]]]
