que1- If you have any, what are your choices for increasing the comparison between different figures on the same graph?

ans1- Matplotlib provides a convenient method called subplots for increasing the comparison between different figures on the same graph. Subplots mean a group of smaller axes (where each axis is a plot) that can exist together within a single figure.

que2- Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?

ans2- Compound interest makes a sum of money grow at a faster rate than simple interest,because in addition to earning returns on the money you invest, you also earn returns on those returns at the end of every compounding period, which could be daily, monthly, quarterly or annually.

que3- What is a histogram, exactly? Name a numpy method for creating such a graph.

ans3- Histogram shows total values of X with respect to Y. Which means at any particular position of X, Y value shows the total number of counts or data below that value of X. `numpy.histogram()` is the built in function used.

que4- If necessary, how do you change the aspect ratios between the X and Y axes?

ans4- We can use __figure(figsize=(10,8))__ function inside the __matplot.pyplot__ library which we scale down or up the graph.

que5- Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.

ans5- 

In [5]:
import numpy as np
v1 = np.array([[1, 2], [1, 2]])
v2 = np.array([[1, 2], [1, 2]])

print("vector multiplication")
print(np.dot(v1, v2))
print("outer multiplication")
print(np.outer(v1, v2))
print("\nElementwise multiplication of two vector")
print(v1 * v2)

vector multiplication
[[3 6]
 [3 6]]
outer multiplication
[[1 2 1 2]
 [2 4 2 4]
 [1 2 1 2]
 [2 4 2 4]]

Elementwise multiplication of two vector
[[1 4]
 [1 4]]


que6- Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?

ans6- `np.pmt(rate, nper, pv)` function we will be using in order to calculate monthly mortgage payment before you purchase a house.

rate = The periodic interest rate

nper = The number of payment periods

pv = The total value of the mortgage loan

que7- Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.

ans7- Yes, an array can store the string. The limitation which imposed on the string data is, whenever we store the data of string dtype then it should should keep in mind that the string which is having the maximum length is the limit.